/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
/**
 *
 * @author Acer
 */
public class Age extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Age.class.getName());

    /**
     * Creates new form Age
     */
    
    public Age() {
        this(null);
    }
    
    public Age(JFrame previous) {
        initComponents();
        setLocationRelativeTo(null);
        
        if (previous != null) {
        this.setLocation(previous.getLocation());
    } else {
        this.setLocationRelativeTo(null);
    }
        
        this.setMinimumSize(new java.awt.Dimension(330, 625));
        setPreferredSize(new java.awt.Dimension(330, 580));
        setSize(340, 590);
        setResizable(false);
        
        young.setBorderPainted(false);
        young.setContentAreaFilled(false);
        young.setFocusPainted(false);
        young.setOpaque(false);
        
        young.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/young2.png")));
        
        adult.setBorderPainted(false);
        adult.setContentAreaFilled(false);
        adult.setFocusPainted(false);
        adult.setOpaque(false);
        
        adult.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/adult2.png")));
        
        old.setBorderPainted(false);
        old.setContentAreaFilled(false);
        old.setFocusPainted(false);
        old.setOpaque(false);
        
        old.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/old2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        old = new javax.swing.JButton();
        young = new javax.swing.JButton();
        adult = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        text1.setBackground(new java.awt.Color(31, 119, 245));
        text1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        text1.setForeground(new java.awt.Color(31, 119, 245));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("<html><div style='text-align: center;'>How Old Are You?</div></html>");
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        old.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/old1.png"))); // NOI18N
        old.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        old.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oldActionPerformed(evt);
            }
        });

        young.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/young1.png"))); // NOI18N
        young.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        young.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youngActionPerformed(evt);
            }
        });

        adult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/adult1.png"))); // NOI18N
        adult.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        adult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(old, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(young, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adult, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(young)
                .addGap(18, 18, 18)
                .addComponent(adult)
                .addGap(18, 18, 18)
                .addComponent(old)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void oldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oldActionPerformed
        updateAgeToDatabse("30+ years");
        
        body bodyPage = new body(this);  
        bodyPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_oldActionPerformed

    private void youngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youngActionPerformed
        updateAgeToDatabse("15-19 years");
        
        body bodyPage = new body(this);  
        bodyPage.setVisible(true);
        this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_youngActionPerformed

    private void adultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultActionPerformed
        updateAgeToDatabse("20-29 years");
        
        body bodyPage = new body(this);  
        bodyPage.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_adultActionPerformed

    private void updateAgeToDatabse(String age) {
        Connection conn = null;
        PreparedStatement ps = null;
        
        try {
            conn = DBConnection.getConnection();
            
            if (conn == null) {
                System.err.println("❌ ERROR: Koneksi database gagal!");
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Gagal terhubung ke database!", 
                    "Connection Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String sql = "UPDATE users SET age = ? WHERE id = ?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, age);
            ps.setLong(2, start.Session.userId);
            
            int rowsAffected = ps.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("✅ Age '" + age + "' berhasil disimpan untuk User ID: " + start.Session.userId);
            } else {
                System.out.println("⚠️ Gagal mengupdate age - User ID tidak ditemukan");
            }
            
        } catch (Exception e) {
            System.err.println("❌ Error saat update age:");
            e.printStackTrace();
        } finally {
            try {
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Age().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adult;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton old;
    private javax.swing.JLabel text1;
    private javax.swing.JButton young;
    // End of variables declaration//GEN-END:variables
}
