/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author Acer
 */
public class bmi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(bmi.class.getName());

    private double bmiValue = 0.0;
    private String bmiCategory = "";
    /**
     * Creates new form bmi
     */
    public bmi(JFrame previous) {
        initComponents();
        setLocationRelativeTo(null);
        
        if (previous != null) {
        this.setLocation(previous.getLocation());
    } else {
        this.setLocationRelativeTo(null);
    }
        
        this.setMinimumSize(new java.awt.Dimension(330, 625));
        setPreferredSize(new java.awt.Dimension(330, 580));
        setSize(340, 590);
        setResizable(false);
        
        confirmblue.setBorderPainted(false);
        confirmblue.setContentAreaFilled(false);
        confirmblue.setFocusPainted(false);
        confirmblue.setOpaque(false);
        
        confirmblue.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nextwhite2.png")));
        
        calculateAndDisplayBMI();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        confirmblue = new javax.swing.JButton();
        text2 = new javax.swing.JLabel();
        text3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(31, 119, 245));

        text1.setBackground(new java.awt.Color(31, 119, 245));
        text1.setFont(new java.awt.Font("Segoe UI", 1, 100)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 255, 255));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("XX");
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        confirmblue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nextwhite1.png"))); // NOI18N
        confirmblue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        confirmblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmblueActionPerformed(evt);
            }
        });

        text2.setBackground(new java.awt.Color(31, 119, 245));
        text2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        text2.setForeground(new java.awt.Color(255, 255, 255));
        text2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text2.setText("XXXXXXXXXX");
        text2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        text3.setBackground(new java.awt.Color(31, 119, 245));
        text3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        text3.setForeground(new java.awt.Color(255, 255, 255));
        text3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text3.setText("<html><div style='text-align: center;'>Here’s Your Glow Summary</div></html>");
        text3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(confirmblue, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(text3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                    .addComponent(text2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(text3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(text2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(confirmblue)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Method untuk ambil height dan weight dari database, hitung BMI, dan tampilkan
     */
    private void calculateAndDisplayBMI() {
    Connection conn = null;
    PreparedStatement ps = null;
    ResultSet rs = null;
    
    try {
        conn = DBConnection.getConnection();
        
        if (conn == null) {
            System.err.println("❌ ERROR: Koneksi database gagal!");
            text1.setText("ERROR");
            return;
        }
        
        // Ambil height dan weight dari database
        String sql = "SELECT height_cm, weight_kg FROM users WHERE id = ?";
        ps = conn.prepareStatement(sql);
        ps.setLong(1, start.Session.userId);
        
        rs = ps.executeQuery();
        
        if (rs.next()) {
            // Ambil data dari ResultSet dengan error handling
            int heightCm = 0;
            int weightKg = 0;
            
            try {
                heightCm = rs.getInt("height_cm");
                weightKg = rs.getInt("weight_kg");
            } catch (Exception e) {
                System.err.println("❌ Error mengambil data height/weight: " + e.getMessage());
                text1.setText("ERROR");
                return;
            }
            
            // Validasi data
            if (heightCm <= 0 || weightKg <= 0) {
                System.err.println("⚠️ Height atau Weight tidak valid!");
                text1.setText("N/A");
                return;
            }
            
            // Hitung BMI: weight(kg) / (height(m))²
            double heightM = heightCm / 100.0; // Convert cm to meter
            bmiValue = weightKg / (heightM * heightM);
            
            // Tentukan kategori BMI
            if (bmiValue < 18.5) {
                bmiCategory = "underweight";
            } else if (bmiValue >= 18.5 && bmiValue < 25) {
                bmiCategory = "normal";
            } else if (bmiValue >= 25 && bmiValue < 30) {
                bmiCategory = "overweight";
            } else {
                bmiCategory = "obese";
            }
            
            // Display BMI value (rounded to 1 decimal place)
            String bmiDisplay = String.format("%.1f", bmiValue);
            text1.setText(bmiDisplay);
            
            // Display kategori
            text2.setText("<html><div style='text-align: center;'>" + bmiCategory.toUpperCase() + "</div></html>");
            
            // Simpan ke database
            saveBMIToDatabase(bmiValue, bmiCategory);
            
            System.out.println("✅ BMI Calculated:");
            System.out.println("   Height: " + heightCm + " cm");
            System.out.println("   Weight: " + weightKg + " kg");
            System.out.println("   BMI Value: " + String.format("%.2f", bmiValue));
            System.out.println("   Category: " + bmiCategory);
            
        } else {
            System.err.println("⚠️ User tidak ditemukan di database");
            text1.setText("N/A");
        }
        
    } catch (Exception e) {
        System.err.println("❌ Error saat menghitung BMI:");
        System.err.println("   Error: " + e.getMessage());
        e.printStackTrace();
        text1.setText("ERROR");
    } finally {
        try {
            if (rs != null) rs.close();
            if (ps != null) ps.close();
            if (conn != null) conn.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
    
    /**
     * Method untuk menyimpan BMI value dan category ke database
     */
    private void saveBMIToDatabase(double bmiValue, String bmiCategory) {
        Connection conn = null;
        PreparedStatement ps = null;
        
        try {
            conn = DBConnection.getConnection();
            
            if (conn == null) {
                System.err.println("❌ ERROR: Koneksi database gagal!");
                return;
            }
            
            String sql = "UPDATE users SET bmi_value = ?, bmi_category = ? WHERE id = ?";
            ps = conn.prepareStatement(sql);
            ps.setDouble(1, bmiValue);
            ps.setString(2, bmiCategory);
            ps.setLong(3, start.Session.userId);
            
            int rowsAffected = ps.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("✅ BMI data berhasil disimpan ke database!");
            } else {
                System.out.println("⚠️ Gagal mengupdate BMI data - User ID tidak ditemukan");
            }
            
        } catch (Exception e) {
            System.err.println("❌ Error saat menyimpan BMI ke database:");
            e.printStackTrace();
        } finally {
            try {
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    private void confirmblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmblueActionPerformed
        skintype skintype = new skintype(this);
        skintype.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_confirmblueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info :
                javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> new Outro(null).setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmblue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text1;
    private javax.swing.JLabel text2;
    private javax.swing.JLabel text3;
    // End of variables declaration//GEN-END:variables
}
