
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class body extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(body.class.getName());

    /**
     * Creates new form body
     */
    public body() {
        this(null);
    }
    
    public body(JFrame previous) {
        initComponents();
        setLocationRelativeTo(null);
        
        if (previous != null) {
        this.setLocation(previous.getLocation());
    } else {
        this.setLocationRelativeTo(null);
    }
        this.setMinimumSize(new java.awt.Dimension(330, 625));
        setPreferredSize(new java.awt.Dimension(330, 580));
        setSize(340, 590);
        setResizable(false);
        
        confirmblue.setBorderPainted(false);
        confirmblue.setContentAreaFilled(false);
        confirmblue.setFocusPainted(false);
        confirmblue.setOpaque(false);
        
        confirmblue.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/confirmblue2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        confirmblue = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        HeightTF = new javax.swing.JTextField();
        WeightTF = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        text1.setBackground(new java.awt.Color(31, 119, 245));
        text1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        text1.setForeground(new java.awt.Color(31, 119, 245));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("<html><div style='text-align: center;'>Tell Us About Your Body!</div></html>");
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        confirmblue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/confirmblue1.png"))); // NOI18N
        confirmblue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        confirmblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmblueActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(31, 119, 245));
        jLabel1.setText("Height");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(31, 119, 245));
        jLabel2.setText("Weight");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(31, 119, 245));
        jLabel3.setText("Kg");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(31, 119, 245));
        jLabel4.setText("Cm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(HeightTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(WeightTF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6))
                    .addComponent(confirmblue, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(HeightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(WeightTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(confirmblue)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmblueActionPerformed
    if (HeightTF.getText().trim().isEmpty() || WeightTF.getText().trim().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Silakan isi height dan weight!", 
                "Input Error", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        try {
            int height = Integer.parseInt(HeightTF.getText().trim());
            int weight = Integer.parseInt(WeightTF.getText().trim());
            
            // Simpan ke database
            saveBodyData(height, weight);
            
            // Lanjut ke halaman skin
            skin skinPage = new skin(this);  
            skinPage.setVisible(true);
            this.dispose();
            
        } catch (NumberFormatException e) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Height dan Weight harus berupa angka!", 
                "Input Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_confirmblueActionPerformed

    private void saveBodyData(int height, int weight) {
        Connection conn = null;
        PreparedStatement ps = null;
        
        try {
            conn = DBConnection.getConnection();
            
            if (conn == null) {
                System.err.println("❌ ERROR: Koneksi database gagal!");
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Gagal terhubung ke database!", 
                    "Connection Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String sql = "UPDATE users SET height_cm = ?, weight_kg = ? WHERE id = ?";
            ps = conn.prepareStatement(sql);
            ps.setInt(1, height);
            ps.setInt(2, weight);
            ps.setLong(3, start.Session.userId);
            
            int rowsAffected = ps.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("✅ Body data berhasil disimpan!");
                System.out.println("   Height: " + height + " cm");
                System.out.println("   Weight: " + weight + " kg");
                System.out.println("   User ID: " + start.Session.userId);
            } else {
                System.out.println("⚠️ Gagal mengupdate body data - User ID tidak ditemukan");
            }
            
        } catch (Exception e) {
            System.err.println("❌ Error saat menyimpan body data:");
            e.printStackTrace();
        } finally {
            try {
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new body().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField HeightTF;
    private javax.swing.JTextField WeightTF;
    private javax.swing.JButton confirmblue;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text1;
    // End of variables declaration//GEN-END:variables
}
