
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class budget extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(budget.class.getName());

    /**
     * Creates new form budget
     */
    public budget() {
    this(null);
}

    public budget(JFrame previous) {
        initComponents();
        setLocationRelativeTo(null);
        
        if (previous != null) {
        this.setLocation(previous.getLocation());
    } else {
        this.setLocationRelativeTo(null);
    }
        
        this.setMinimumSize(new java.awt.Dimension(330, 625));
        setPreferredSize(new java.awt.Dimension(330, 580));
        setSize(340, 590);
        setResizable(false);
        
        poor.setBorderPainted(false);
        poor.setContentAreaFilled(false);
        poor.setFocusPainted(false);
        poor.setOpaque(false);
        
        poor.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/0k2.png")));
        
        rich.setBorderPainted(false);
        rich.setContentAreaFilled(false);
        rich.setFocusPainted(false);
        rich.setOpaque(false);
        
        rich.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/500K2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        poor = new javax.swing.JButton();
        rich = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        text1.setBackground(new java.awt.Color(31, 119, 245));
        text1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        text1.setForeground(new java.awt.Color(31, 119, 245));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("<html><div style='text-align: center;'>How High is Your Budget?</div></html>");
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        poor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/0k1.png"))); // NOI18N
        poor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        poor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poorActionPerformed(evt);
            }
        });

        rich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/500k1.png"))); // NOI18N
        rich.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        rich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                richActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(rich))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(poor))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(poor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rich)
                .addGap(0, 272, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poorActionPerformed
       saveBudgetLevel("low");
        
        bmi bmiPage = new bmi(this);
       bmiPage.setVisible(true);
       this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_poorActionPerformed

    private void richActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_richActionPerformed
       saveBudgetLevel("high");
        
        bmi bmiPage = new bmi(this);
       bmiPage.setVisible(true);
       this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_richActionPerformed

   public void saveBudgetLevel(String budgetLevel) {
        // === [TAMBAHAN WAJIB] SIMPAN KE MEMORI ===
        // Logika: Jika "low" maka isBudget = true (Hemat)
        // Jika "high" maka isBudget = false (Sultan)
        
        if (budgetLevel.equalsIgnoreCase("low")) {
            UserData.isBudget = true;
        } else {
            UserData.isBudget = false;
        }
        
        System.out.println("DEBUG: UserData.isBudget diisi: " + UserData.isBudget);
        // ==========================================

        Connection conn = null;
        PreparedStatement ps = null;
        
        try {
            conn = DBConnection.getConnection();
            
            if (conn == null) {
                System.err.println("❌ ERROR: Koneksi database gagal!");
                return;
            }
            
            String sql = "UPDATE users SET budget_level = ? WHERE id = ?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, budgetLevel);
            ps.setLong(2, start.Session.userId);
            
            int rowsAffected = ps.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("✅ Budget level '" + budgetLevel + "' berhasil disimpan ke DB");
            } 
            
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // ... (kode Look and Feel biarkan saja) ...

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            // Masukkan null agar tidak error saat Run File
            new budget(null).setVisible(true); 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton poor;
    private javax.swing.JButton rich;
    private javax.swing.JLabel text1;
    // End of variables declaration//GEN-END:variables
}
