
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class exercise extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(exercise.class.getName());

    /**
     * Creates new form exercise
     */
    public exercise(JFrame previous) {
        initComponents();
        setLocationRelativeTo(null);
        
        if (previous != null) {
        this.setLocation(previous.getLocation());
    } else {
        this.setLocationRelativeTo(null);
    }
        
        this.setMinimumSize(new java.awt.Dimension(330, 625));
        setPreferredSize(new java.awt.Dimension(330, 580));
        setSize(340, 590);
        setResizable(false);
        
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setFocusPainted(false);
        home.setOpaque(false);
        
        home.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home2.png")));
        
        equipment.setBorderPainted(false);
        equipment.setContentAreaFilled(false);
        equipment.setFocusPainted(false);
        equipment.setOpaque(false);
        
        equipment.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/equipment2.png")));
        
        gym.setBorderPainted(false);
        gym.setContentAreaFilled(false);
        gym.setFocusPainted(false);
        gym.setOpaque(false);
        
        gym.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/gym2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        home = new javax.swing.JButton();
        equipment = new javax.swing.JButton();
        gym = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        text1.setBackground(new java.awt.Color(31, 119, 245));
        text1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        text1.setForeground(new java.awt.Color(31, 119, 245));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("<html><div style='text-align: center;'>Where and With What Do You Exercise?</div></html>");
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/home1.png"))); // NOI18N
        home.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        equipment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/equipment1.png"))); // NOI18N
        equipment.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        equipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentActionPerformed(evt);
            }
        });

        gym.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/gym1.png"))); // NOI18N
        gym.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gymActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(equipment, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(gym, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(equipment)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gym)
                .addContainerGap(244, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        saveExerciseType("home");
        
        budget budgetPage = new budget(this);
        budgetPage.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void equipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentActionPerformed
        saveExerciseType("equipment");
        
        budget budgetPage = new budget(this);
        budgetPage.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentActionPerformed

    private void gymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gymActionPerformed
        saveExerciseType("gym");
        
        budget budgetPage = new budget(this);
        budgetPage.setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_gymActionPerformed

    private void saveExerciseType(String exerciseType) {
        Connection conn = null;
        PreparedStatement ps = null;
        
        try {
            conn = DBConnection.getConnection();
            
            if (conn == null) {
                System.err.println("❌ ERROR: Koneksi database gagal!");
                javax.swing.JOptionPane.showMessageDialog(this, 
                    "Gagal terhubung ke database!", 
                    "Connection Error", 
                    javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            String sql = "UPDATE users SET exercise_type = ? WHERE id = ?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, exerciseType);
            ps.setLong(2, start.Session.userId);
            
            int rowsAffected = ps.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("✅ Exercise type '" + exerciseType + "' berhasil disimpan untuk User ID: " + start.Session.userId);
            } else {
                System.out.println("⚠️ Gagal mengupdate exercise type - User ID tidak ditemukan");
            }
            
        } catch (Exception e) {
            System.err.println("❌ Error saat menyimpan exercise type:");
            e.printStackTrace();
        } finally {
            try {
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info :
                javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> new Outro(null).setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton equipment;
    private javax.swing.JButton gym;
    private javax.swing.JButton home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel text1;
    // End of variables declaration//GEN-END:variables
}
