/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
/**
 *
 * @author Acer
 */
public class Gender extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Gender.class.getName());

    /**
     * Creates new form Gender
     */
    public Gender() {
        this(null);
    }
    
    public Gender(JFrame previous) {
        initComponents();
        
        if (previous != null) {
        this.setLocation(previous.getLocation());
    } else {
        this.setLocationRelativeTo(null); // center if no previous frame
    }
        
        this.setMinimumSize(new java.awt.Dimension(330, 625));
        setPreferredSize(new java.awt.Dimension(330, 580));
        setSize(340, 590);
        setResizable(false);
        
        
        male1.setBorderPainted(false);
        male1.setContentAreaFilled(false);
        male1.setFocusPainted(false);
        male1.setOpaque(false);
        
        male1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/male2.png")));
        
        female1.setBorderPainted(false);
        female1.setContentAreaFilled(false);
        female1.setFocusPainted(false);
        female1.setOpaque(false);
        
        female1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/female2.png")));
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        male1 = new javax.swing.JButton();
        female1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(330, 580));
        setMinimumSize(new java.awt.Dimension(330, 580));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        text1.setBackground(new java.awt.Color(31, 119, 245));
        text1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        text1.setForeground(new java.awt.Color(31, 119, 245));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("<html><div style='text-align: center;'>Whats Your Gender?</div></html>");
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        male1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/male1.png"))); // NOI18N
        male1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        male1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                male1ActionPerformed(evt);
            }
        });

        female1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/female1.png"))); // NOI18N
        female1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        female1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(32, Short.MAX_VALUE)
                        .addComponent(male1)
                        .addGap(18, 18, 18)
                        .addComponent(female1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(male1)
                    .addComponent(female1))
                .addContainerGap(245, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void male1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_male1ActionPerformed
        updateGenderToDatabase("male");
        
        Age agePage = new Age(this);  
        agePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_male1ActionPerformed

    private void female1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female1ActionPerformed
        updateGenderToDatabase("female");
        
        Age agePage = new Age(this); 
        agePage.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_female1ActionPerformed

    private void updateGenderToDatabase(String gender) {
    java.sql.Connection conn = null;
    java.sql.PreparedStatement ps = null;
    
    try {
        // Ambil connection baru
        conn = DBConnection.getConnection();
        
        // Jika connection masih null setelah 3 percobaan, batalkan
        int attempts = 0;
        while ((conn == null || conn.isClosed()) && attempts < 3) {
            System.out.println("Attempt " + (attempts + 1) + ": Membuat koneksi baru...");
            conn = DBConnection.getConnection();
            attempts++;
            Thread.sleep(500); // Tunggu 500ms
        }
        
        // Jika tetap gagal, tampilkan error
        if (conn == null || conn.isClosed()) {
            System.out.println("FATAL ERROR: Tidak bisa membuat koneksi ke database!");
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Gagal terhubung ke database. Silakan cek koneksi internet.", 
                "Connection Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        // Jika connection valid, jalankan query
        String sql = "UPDATE users SET gender = ? WHERE id = ?";
        ps = conn.prepareStatement(sql);
        ps.setString(1, gender);
        ps.setLong(2, start.Session.userId);
        
        int rowsAffected = ps.executeUpdate();
        
        if (rowsAffected > 0) {
            System.out.println("✓ Gender '" + gender + "' berhasil disimpan untuk User ID: " + start.Session.userId);
        } else {
            System.out.println("✗ Gagal mengupdate gender - User ID tidak ditemukan");
        }
        
    } catch (java.sql.SQLException e) {
        System.out.println("SQL Error saat update gender:");
        e.printStackTrace();
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error Database: " + e.getMessage(), 
            "Database Error", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    } catch (InterruptedException e) {
        System.out.println("Thread interrupted:");
        e.printStackTrace();
    } catch (Exception e) {
        System.out.println("Error saat update gender:");
        e.printStackTrace();
    } finally {
        try {
            if (ps != null) {
                ps.close();
            }
            if (conn != null && !conn.isClosed()) {
                conn.close();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Gender().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton female1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton male1;
    private javax.swing.JLabel text1;
    // End of variables declaration//GEN-END:variables
}
