/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import java.sql.Connection;
/**
 *
 * @author Acer
 */
public class Intro extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Intro.class.getName());

private FadePanel fadeBlue;
private FadePanel fadeWhite;

private void setupFade() {

    fadeBlue = new FadePanel();
    fadeWhite = new FadePanel();

    // Sama ukuran & posisi panel asli
    fadeBlue.setBounds(bgblue1.getBounds());
    fadeWhite.setBounds(bgwhite.getBounds());

    // Tambahkan panel asli sebagai anak dari FadePanel
    fadeBlue.setLayout(new java.awt.BorderLayout());
    fadeWhite.setLayout(new java.awt.BorderLayout());

    fadeBlue.add(bgblue1);
    fadeWhite.add(bgwhite);

    // Letakkan fade panel di container
    getContentPane().add(fadeBlue);
    getContentPane().add(fadeWhite);

    // Atur visibilitas awal
    fadeBlue.setVisible(false);  // panel kedua nanti muncul
    fadeWhite.setVisible(true);  // panel pertama tampil dulu
}

private void fadeSwitch(FadePanel from, FadePanel to, boolean openStartAfter) {

    to.setOpacity(0f);
    to.setVisible(true);

    final float[] progress = {0f};
    final float speed = 0.015f;

    javax.swing.Timer timer = new javax.swing.Timer(20, null);

    timer.addActionListener(e -> {

        progress[0] += speed;
        if (progress[0] > 1f) progress[0] = 1f;

        float eased = (float)(1 - Math.pow(1 - progress[0], 3));

        from.setOpacity(1f - eased);
        to.setOpacity(eased);

        if (progress[0] >= 1f) {
            from.setVisible(false);
            timer.stop();

            if (openStartAfter) {
                navigateBasedOnDatabase();
                dispose(); // tutup splash screen
            }
        }
    });

    timer.start();
}
   private void navigateBasedOnDatabase() {
    try {
        // Dapatkan connection dari DBConnection
        Connection conn = DBConnection.getConnection();
        
        if (DatabaseChecker.isConnected(conn)) {
            // Cek apakah tabel users kosong
            boolean isEmpty = DatabaseChecker.isUsersTableEmpty(conn);
            
            if (isEmpty) {
                // Database kosong -> ke start (setup awal)
                new start().setVisible(true);
                logger.info("Tabel users kosong, navigasi ke start.java");
            } else {
                // Database ada data -> ambil userId dan set ke Session, lalu ke Main
                long userId = DatabaseChecker.getFirstUserIdFromDatabase(conn);
                
                if (userId > 0) {
                    // Set userId ke Session
                    start.Session.userId = userId;
                    
                    // Buka Main
                    new Main(this).setVisible(true);
                    logger.info("User ID " + userId + " di-set ke Session, navigasi ke Main.java");
                } else {
                    // Jika gagal ambil userId, fallback ke start
                    new start().setVisible(true);
                    logger.warning("Gagal ambil userId, navigasi ke start.java");
                }
            }
            
            conn.close();
        } else {
            // Jika koneksi gagal, default ke start
            new start().setVisible(true);
            logger.warning("Koneksi database gagal, navigasi ke start.java");
        }
        
        dispose(); // tutup splash screen
        
    } catch (Exception e) {
        logger.log(java.util.logging.Level.SEVERE, "Error saat check database: " + e.getMessage());
        // Fallback ke start jika ada error
        new start().setVisible(true);
        dispose();
    }
}


    /**
     * Creates new form newuser
     */
    public Intro() {
        initComponents();
        this.setLocationRelativeTo(null);
        setupFade();
        
        fadeBlue.add(bgblue1);
        fadeWhite.add(bgwhite);

        javax.swing.Timer delay = new javax.swing.Timer(1000, e -> {
            fadeSwitch(fadeWhite, fadeBlue, true); // true = setelah fade selesai buka start
        });
        delay.setRepeats(false);
        delay.start();  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgblue1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        bgwhite = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        bgblue1.setBackground(new java.awt.Color(31, 119, 245));

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("GlowMax");
        title.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout bgblue1Layout = new javax.swing.GroupLayout(bgblue1);
        bgblue1.setLayout(bgblue1Layout);
        bgblue1Layout.setHorizontalGroup(
            bgblue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        bgblue1Layout.setVerticalGroup(
            bgblue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgblue1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(291, Short.MAX_VALUE))
        );

        bgwhite.setBackground(new java.awt.Color(255, 255, 255));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/mainlogo.png"))); // NOI18N
        logo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout bgwhiteLayout = new javax.swing.GroupLayout(bgwhite);
        bgwhite.setLayout(bgwhiteLayout);
        bgwhiteLayout.setHorizontalGroup(
            bgwhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgwhiteLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(logo)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        bgwhiteLayout.setVerticalGroup(
            bgwhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgwhiteLayout.createSequentialGroup()
                .addGap(220, 220, 220)
                .addComponent(logo)
                .addContainerGap(241, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgwhite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgblue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgwhite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(bgblue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Intro().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgblue1;
    private javax.swing.JPanel bgwhite;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
