
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author Acer
 */
public class Main extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Main.class.getName());

    /**
     * Creates new form mainpage
     */
    public Main(JFrame previous) {
        initComponents();
        
        setLocationRelativeTo(null);
        
        if (previous != null) {
        this.setLocation(previous.getLocation());
    } else {
        this.setLocationRelativeTo(null);
    }
        
        this.setMinimumSize(new java.awt.Dimension(330, 625));
        setPreferredSize(new java.awt.Dimension(330, 580));
        setSize(340, 590);
        setResizable(false);
        
        stats.setBorderPainted(false);
        stats.setContentAreaFilled(false);
        stats.setFocusPainted(false);
        stats.setOpaque(false);
        
        stats.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/stats2.png")));
        
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setFocusPainted(false);
        home.setOpaque(false);
        
        workout.setBorderPainted(false);
        workout.setContentAreaFilled(false);
        workout.setFocusPainted(false);
        workout.setOpaque(false);
        
        food.setBorderPainted(false);
        food.setContentAreaFilled(false);
        food.setFocusPainted(false);
        food.setOpaque(false);
        
        skin.setBorderPainted(false);
        skin.setContentAreaFilled(false);
        skin.setFocusPainted(false);
        skin.setOpaque(false);
        
        loadRandomDailyTasks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        stats = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        workout = new javax.swing.JButton();
        skin = new javax.swing.JButton();
        food = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        dl3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        dl1 = new javax.swing.JLabel();
        dl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 31, 35));

        text1.setBackground(new java.awt.Color(31, 119, 245));
        text1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 255, 255));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("<html><div style='text-align: center;'>GlowMax</div></html>");
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        stats.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/stats.png"))); // NOI18N
        stats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statsActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(61, 76, 85));

        jPanel3.setBackground(new java.awt.Color(20, 31, 35));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/main2.png"))); // NOI18N
        home.setToolTipText("");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        workout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/workout1.png"))); // NOI18N
        workout.setToolTipText("");
        workout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workoutActionPerformed(evt);
            }
        });

        skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/skin2.png"))); // NOI18N
        skin.setToolTipText("");
        skin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skinActionPerformed(evt);
            }
        });

        food.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/food1.png"))); // NOI18N
        food.setToolTipText("");
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(workout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(skin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(workout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(skin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(food, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dl3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        dl3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dl3.setText("dl3");
        jLayeredPane1.setLayer(dl3, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(dl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 80, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/daily quest.png"))); // NOI18N
        jLayeredPane1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 5, 310, 130));

        dl1.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        dl1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dl1.setText("dl1");
        jLayeredPane1.setLayer(dl1, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(dl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 80, -1));

        dl2.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        dl2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        dl2.setText("dl2");
        jLayeredPane1.setLayer(dl2, javax.swing.JLayeredPane.POPUP_LAYER);
        jLayeredPane1.add(dl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 80, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(stats, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addComponent(text1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stats, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadRandomDailyTasks() {
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        try {
            conn = DBConnection.getConnection();
            
            if (conn == null) {
                System.err.println("❌ ERROR: Koneksi database gagal!");
                dl1.setText("Error");
                dl2.setText("Error");
                dl3.setText("Error");
                return;
            }
            
            // Ambil SEMUA tasks dari database
            String sql = "SELECT title FROM daily_tasks ORDER BY RAND() LIMIT 3";
            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();
            
            List<String> tasks = new ArrayList<>();
            
            while (rs.next()) {
                String taskTitle = rs.getString("title");
                tasks.add(taskTitle);
            }
            
            System.out.println("✅ Daily Tasks Loaded:");
            
            // Display 3 tasks ke label
            if (tasks.size() >= 1) {
                dl1.setText(tasks.get(0));
                System.out.println("   Task 1: " + tasks.get(0));
            } else {
                dl1.setText("No task");
            }
            
            if (tasks.size() >= 2) {
                dl2.setText(tasks.get(1));
                System.out.println("   Task 2: " + tasks.get(1));
            } else {
                dl2.setText("No task");
            }
            
            if (tasks.size() >= 3) {
                dl3.setText(tasks.get(2));
                System.out.println("   Task 3: " + tasks.get(2));
            } else {
                dl3.setText("No task");
            }
            
        } catch (Exception e) {
            System.err.println("❌ Error saat load daily tasks:");
            System.err.println("   Error Message: " + e.getMessage());
            e.printStackTrace();
            dl1.setText("Error");
            dl2.setText("Error");
            dl3.setText("Error");
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    private void statsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statsActionPerformed
        stats statsPage = new stats(this);
        statsPage.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_statsActionPerformed

    private void workoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workoutActionPerformed
        Workout MondayPage = new Workout(this);
        MondayPage.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_workoutActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Main mainpagePage = new Main(this);
        mainpagePage.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        Calories TEST1Page = new Calories(this);
        TEST1Page.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_foodActionPerformed

    private void skinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skinActionPerformed
        Skincare SkincareFrameV2Page = new Skincare(this);
        SkincareFrameV2Page.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_skinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info :
                javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
        java.awt.EventQueue.invokeLater(() -> new Main(null).setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dl1;
    private javax.swing.JLabel dl2;
    private javax.swing.JLabel dl3;
    private javax.swing.JButton food;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton skin;
    private javax.swing.JButton stats;
    private javax.swing.JLabel text1;
    private javax.swing.JButton workout;
    // End of variables declaration//GEN-END:variables
}
