
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class skin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(skin.class.getName());

    /**
     * Creates new form skin
     */
    public skin(JFrame previous) {
        initComponents();
        setLocationRelativeTo(null);
        
        if (previous != null) {
        this.setLocation(previous.getLocation());
    } else {
        this.setLocationRelativeTo(null);
    }
        
        this.setMinimumSize(new java.awt.Dimension(330, 625));
        setPreferredSize(new java.awt.Dimension(330, 580));
        setSize(340, 590);
        setResizable(false);
        
        normal.setBorderPainted(false);
        normal.setContentAreaFilled(false);
        normal.setFocusPainted(false);
        normal.setOpaque(false);
        
        normal.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/normal2.png")));
        
        oily.setBorderPainted(false);
        oily.setContentAreaFilled(false);
        oily.setFocusPainted(false);
        oily.setOpaque(false);
        
        oily.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/oily2.png")));
        
        dry.setBorderPainted(false);
        dry.setContentAreaFilled(false);
        dry.setFocusPainted(false);
        dry.setOpaque(false);
        
        dry.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dry2.png")));
        
        combination.setBorderPainted(false);
        combination.setContentAreaFilled(false);
        combination.setFocusPainted(false);
        combination.setOpaque(false);
        
        combination.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/combination2.png")));
        
        sensitive.setBorderPainted(false);
        sensitive.setContentAreaFilled(false);
        sensitive.setFocusPainted(false);
        sensitive.setOpaque(false);
        
        sensitive.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sensitive2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        normal = new javax.swing.JButton();
        oily = new javax.swing.JButton();
        dry = new javax.swing.JButton();
        combination = new javax.swing.JButton();
        sensitive = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        text1.setBackground(new java.awt.Color(31, 119, 245));
        text1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        text1.setForeground(new java.awt.Color(31, 119, 245));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("<html><div style='text-align: center;'>How Would You Describe Your Skin Type?</div></html>");
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        normal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/normal1.png"))); // NOI18N
        normal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                normalActionPerformed(evt);
            }
        });

        oily.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/oily1.png"))); // NOI18N
        oily.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        oily.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oilyActionPerformed(evt);
            }
        });

        dry.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dry1.png"))); // NOI18N
        dry.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        dry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dryActionPerformed(evt);
            }
        });

        combination.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/combination1.png"))); // NOI18N
        combination.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        combination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combinationActionPerformed(evt);
            }
        });

        sensitive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sensitive1.png"))); // NOI18N
        sensitive.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        sensitive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sensitiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(normal, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(text1, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sensitive, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combination, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dry, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(oily, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(normal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(oily)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dry)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combination)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(sensitive)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_normalActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Mohon maaf, stok rekomendasi untuk kulit Normal sedang kosong.\nSilakan pilih tipe lain.",
            "Info Stok", 
            javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_normalActionPerformed

    private void oilyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oilyActionPerformed
        saveSkinType("oily"); 
        
        exercise exercise = new exercise(this);
        exercise.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_oilyActionPerformed

    private void dryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dryActionPerformed
        saveSkinType("dry"); 
        
        exercise exercise = new exercise(this);
        exercise.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_dryActionPerformed

    private void combinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combinationActionPerformed
        saveSkinType("combination"); 
        
        exercise exercise = new exercise(this);
        exercise.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_combinationActionPerformed

    private void sensitiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sensitiveActionPerformed
        saveSkinType("sensitive"); 
        
        exercise exercise = new exercise(this);
        exercise.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_sensitiveActionPerformed
private void saveSkinType(String skinType) {
        // === [TAMBAHAN WAJIB] SIMPAN KE MEMORI AGAR DIBACA HALAMAN SKINCARE ===
        
        // Pastikan huruf kapital di depan agar cocok dengan Database (Oily, Dry, dll)
        String skinFix = skinType.substring(0, 1).toUpperCase() + skinType.substring(1);
        UserData.skinType = skinFix;
        
        System.out.println("DEBUG: UserData.skinType diisi dengan: " + UserData.skinType);
        // ======================================================================

        Connection conn = null;
        PreparedStatement ps = null;
        
        try {
            conn = DBConnection.getConnection();
            
            if (conn == null) {
                System.err.println("❌ ERROR: Koneksi database gagal!");
                return;
            }
            
            String sql = "UPDATE users SET skin_type = ? WHERE id = ?";
            ps = conn.prepareStatement(sql);
            ps.setString(1, skinType); // Ke database boleh huruf kecil (sesuai enum mysql)
            ps.setLong(2, start.Session.userId);
            
            int rowsAffected = ps.executeUpdate();
            
            if (rowsAffected > 0) {
                System.out.println("✅ Skin type '" + skinType + "' berhasil disimpan ke DB");
            } 
            
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            try {
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // ... (kode Look and Feel biarkan saja) ...

        java.awt.EventQueue.invokeLater(() -> {
            // Masukkan 'null' karena ini cuma tes run file
            new skin(null).setVisible(true); 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton combination;
    private javax.swing.JButton dry;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton normal;
    private javax.swing.JButton oily;
    private javax.swing.JButton sensitive;
    private javax.swing.JLabel text1;
    // End of variables declaration//GEN-END:variables
}
