
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Rizky
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

public class Skincare extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Skincare.class.getName());

    /**
     * Creates new form SkincareFrameV2
     */
    public Skincare(JFrame previous) {
        initComponents();
        this.setMinimumSize(new java.awt.Dimension(330, 625));
        setPreferredSize(new java.awt.Dimension(330, 580));
        setSize(340, 590);
        setResizable(false);
        
        setLocationRelativeTo(null);
        
        if (previous != null) {
        this.setLocation(previous.getLocation());
    } else {
        this.setLocationRelativeTo(null);
    }
        
        home.setBorderPainted(false);
        home.setContentAreaFilled(false);
        home.setFocusPainted(false);
        home.setOpaque(false);
        
        workout.setBorderPainted(false);
        workout.setContentAreaFilled(false);
        workout.setFocusPainted(false);
        workout.setOpaque(false);
        
        food.setBorderPainted(false);
        food.setContentAreaFilled(false);
        food.setFocusPainted(false);
        food.setOpaque(false);
        
        skin.setBorderPainted(false);
        skin.setContentAreaFilled(false);
        skin.setFocusPainted(false);
        skin.setOpaque(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        home = new javax.swing.JButton();
        workout = new javax.swing.JButton();
        skin = new javax.swing.JButton();
        food = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRekomenFaceWash = new javax.swing.JButton();
        lblGambarFaceWash = new javax.swing.JLabel();
        lblNamaFaceWash = new javax.swing.JLabel();
        lblHargaFaceWash = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnRekomenToner = new javax.swing.JButton();
        lblGambarToner = new javax.swing.JLabel();
        lblNamaToner = new javax.swing.JLabel();
        lblHargaToner = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnRekomenSerum = new javax.swing.JButton();
        lblGambarSerum = new javax.swing.JLabel();
        lblNamaSerum = new javax.swing.JLabel();
        lblHargaSerum = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(20, 31, 35));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Morning Skincare Routine");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        jPanel5.setBackground(new java.awt.Color(61, 76, 85));

        jPanel6.setBackground(new java.awt.Color(20, 31, 35));

        home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/main1.png"))); // NOI18N
        home.setToolTipText("");
        home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeActionPerformed(evt);
            }
        });

        workout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/workout1.png"))); // NOI18N
        workout.setToolTipText("");
        workout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workoutActionPerformed(evt);
            }
        });

        skin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/skin2.png"))); // NOI18N
        skin.setToolTipText("");
        skin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                skinActionPerformed(evt);
            }
        });

        food.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/food1.png"))); // NOI18N
        food.setToolTipText("");
        food.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foodActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(home, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(workout, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(food, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(skin, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(workout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(skin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(food, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 330, -1));

        jPanel4.setBackground(new java.awt.Color(20, 31, 35));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Face Wash");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 36, 123, -1));

        btnRekomenFaceWash.setBackground(new java.awt.Color(0, 102, 204));
        btnRekomenFaceWash.setForeground(new java.awt.Color(255, 255, 255));
        btnRekomenFaceWash.setText("Seek Out Recomendation");
        btnRekomenFaceWash.setPreferredSize(new java.awt.Dimension(170, 23));
        btnRekomenFaceWash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRekomenFaceWashActionPerformed(evt);
            }
        });
        jPanel4.add(btnRekomenFaceWash, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 85, -1, -1));

        lblGambarFaceWash.setForeground(new java.awt.Color(255, 255, 255));
        lblGambarFaceWash.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGambarFaceWash.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        lblGambarFaceWash.setOpaque(true);
        jPanel4.add(lblGambarFaceWash, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 21, 95, 87));

        lblNamaFaceWash.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaFaceWash.setText("...");
        jPanel4.add(lblNamaFaceWash, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 114, 291, -1));

        lblHargaFaceWash.setForeground(new java.awt.Color(255, 255, 255));
        lblHargaFaceWash.setText("...");
        jPanel4.add(lblHargaFaceWash, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 120, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, -1));

        jPanel9.setBackground(new java.awt.Color(20, 31, 35));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Toner");
        jPanel9.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 36, 123, -1));

        btnRekomenToner.setBackground(new java.awt.Color(0, 102, 204));
        btnRekomenToner.setForeground(new java.awt.Color(255, 255, 255));
        btnRekomenToner.setText("Seek Out Recomendation");
        btnRekomenToner.setPreferredSize(new java.awt.Dimension(170, 23));
        btnRekomenToner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRekomenTonerActionPerformed(evt);
            }
        });
        jPanel9.add(btnRekomenToner, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 85, -1, -1));

        lblGambarToner.setForeground(new java.awt.Color(255, 255, 255));
        lblGambarToner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGambarToner.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        lblGambarToner.setOpaque(true);
        jPanel9.add(lblGambarToner, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 21, 95, 87));

        lblNamaToner.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaToner.setText("...");
        jPanel9.add(lblNamaToner, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 114, 299, -1));

        lblHargaToner.setForeground(new java.awt.Color(255, 255, 255));
        lblHargaToner.setText("...");
        jPanel9.add(lblHargaToner, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 140, -1));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, -1, -1));

        jPanel11.setBackground(new java.awt.Color(20, 31, 35));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Serum");
        jPanel11.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 41, 123, -1));

        btnRekomenSerum.setBackground(new java.awt.Color(0, 102, 204));
        btnRekomenSerum.setForeground(new java.awt.Color(255, 255, 255));
        btnRekomenSerum.setText("Seek Out Recomendation");
        btnRekomenSerum.setPreferredSize(new java.awt.Dimension(170, 23));
        btnRekomenSerum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRekomenSerumActionPerformed(evt);
            }
        });
        jPanel11.add(btnRekomenSerum, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 85, -1, -1));

        lblGambarSerum.setForeground(new java.awt.Color(255, 255, 255));
        lblGambarSerum.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGambarSerum.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153), 2));
        lblGambarSerum.setOpaque(true);
        jPanel11.add(lblGambarSerum, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 21, 95, 87));

        lblNamaSerum.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaSerum.setText("...");
        jPanel11.add(lblNamaSerum, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 114, 280, -1));

        lblHargaSerum.setForeground(new java.awt.Color(255, 255, 255));
        lblHargaSerum.setText("...");
        jPanel11.add(lblHargaSerum, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 110, -1));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        jPanel3.setBackground(new java.awt.Color(20, 31, 35));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/Bulanv2.png"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 1, 164, 87));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/BULAN BULETv2.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(165, 1, 164, 87));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 89));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRekomenSerumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRekomenSerumActionPerformed
        // TODO add your handling code here:
        tampilkanRekomendasi("Serum", lblNamaSerum, lblGambarSerum, btnRekomenSerum, lblHargaSerum);
    }//GEN-LAST:event_btnRekomenSerumActionPerformed

    private void btnRekomenTonerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRekomenTonerActionPerformed
        // TODO add your handling code here:
        tampilkanRekomendasi("Toner", lblNamaToner, lblGambarToner, btnRekomenToner, lblHargaToner);
    }//GEN-LAST:event_btnRekomenTonerActionPerformed

    private void btnRekomenFaceWashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRekomenFaceWashActionPerformed
        // TODO add your handling code here:
        tampilkanRekomendasi("Face Wash", lblNamaFaceWash, lblGambarFaceWash, btnRekomenFaceWash, lblHargaFaceWash);
    }//GEN-LAST:event_btnRekomenFaceWashActionPerformed

    private void homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeActionPerformed
        Main mainpagePage = new Main(this);
        mainpagePage.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_homeActionPerformed

    private void workoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workoutActionPerformed
        Workout MondayPage = new Workout(this);
        MondayPage.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_workoutActionPerformed

    private void foodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foodActionPerformed
        Calories TEST1Page = new Calories(this);
        TEST1Page.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_foodActionPerformed

    private void skinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_skinActionPerformed
        Skincare SkincareFrameV2Page = new Skincare(this);
        SkincareFrameV2Page.setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_skinActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }
        java.awt.EventQueue.invokeLater(() -> new Skincare(null).setVisible(true));
}



private void tampilkanRekomendasi(String kategori, javax.swing.JLabel lblTeks, javax.swing.JLabel lblGbr, javax.swing.JButton btn, javax.swing.JLabel lblHarga) {
    
    // 1. Ambil Data User
    String skinRaw = UserData.skinType; 
    
    // --- PERBAIKAN: NORMALISASI DATA (Biar cocok sama Database) ---
    // Mengubah "combination" (kecil) menjadi "Combination" (Kapital)
    String skin = "";
    if (skinRaw != null) {
        if (skinRaw.equalsIgnoreCase("oily")) skin = "Oily";
        else if (skinRaw.equalsIgnoreCase("dry")) skin = "Dry";
        else if (skinRaw.equalsIgnoreCase("combination")) skin = "Combination";
        else if (skinRaw.equalsIgnoreCase("sensitive")) skin = "Sensitive";
        else skin = skinRaw; // Jaga-jaga
    }

    // Normalisasi Budget
    String budget = UserData.isBudget ? "Low" : "High"; 

    // Debugging (Cek di Output bawah NetBeans buat memastikan)
    System.out.println("Mencari di DB -> Kategori: " + kategori + " | Skin: " + skin + " | Budget: " + budget);

    // --- PENGAMANAN DATA 'NORMAL' ---
    if (skinRaw != null && skinRaw.equalsIgnoreCase("normal")) {
        lblTeks.setText("Stok Kosong");
        lblHarga.setText("-");
        lblGbr.setIcon(null);
        lblGbr.setText("Belum Tersedia");
        btn.setEnabled(false);
        return;
    }

    try {
        // 2. QUERY SQL
        String sql = "SELECT p.product_name, p.product_image, p.price " +
                     "FROM skincare_products p " +
                     "JOIN skincare_steps s ON p.step_id = s.id " +
                     "WHERE s.name = '" + kategori + "' " +     
                     "AND p.skin_type = '" + skin + "' " +       // Sekarang pakai variabel 'skin' yang sudah Kapital
                     "AND p.budget_level = '" + budget + "'";   

        // 3. Eksekusi ke Database
        java.sql.Connection conn = DBConnection.getConnection(); 
        java.sql.Statement stm = conn.createStatement();
        java.sql.ResultSet res = stm.executeQuery(sql);
        
        // 4. Cek Hasil
        if (res.next()) {
            String namaProduk = res.getString("product_name");
            String pathGambar = res.getString("product_image");
            int harga = res.getInt("price"); 

            // Update UI
            lblTeks.setText(namaProduk);
            
            // Format Harga
            java.text.NumberFormat kurensiIndo = java.text.NumberFormat.getCurrencyInstance(new java.util.Locale("id", "ID"));
            String hargaRupiah = kurensiIndo.format(harga).replace("Rp", "Rp "); 
            lblHarga.setText(hargaRupiah);
            
            // Update Gambar
            try {
                java.net.URL imgURL = getClass().getResource(pathGambar);
                if (imgURL != null) {
                    javax.swing.ImageIcon iconAsli = new javax.swing.ImageIcon(imgURL);
                    java.awt.Image img = iconAsli.getImage().getScaledInstance(lblGbr.getWidth(), lblGbr.getHeight(), java.awt.Image.SCALE_SMOOTH);
                    lblGbr.setIcon(new javax.swing.ImageIcon(img));
                    lblGbr.setText("");
                } else {
                    lblGbr.setIcon(null);
                    lblGbr.setText("Img Error");
                    System.out.println("Gambar tidak ditemukan path: " + pathGambar);
                }
            } catch (Exception e) {
                lblGbr.setText("Error Load");
            }
            
        } else {
            lblTeks.setText("Produk Habis");
            lblHarga.setText("-");
            lblGbr.setIcon(null);
            // Print error di console biar ketahuan kenapa habis
            System.out.println("GAGAL MENEMUKAN DATA UNTUK: " + sql);
        }
        
    } catch (Exception e) {
        System.err.println("Error Database: " + e.getMessage());
        lblTeks.setText("Error DB");
    }

    btn.setEnabled(false);
    btn.setText("Selected");
}
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRekomenFaceWash;
    private javax.swing.JButton btnRekomenSerum;
    private javax.swing.JButton btnRekomenToner;
    private javax.swing.JButton food;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel lblGambarFaceWash;
    private javax.swing.JLabel lblGambarSerum;
    private javax.swing.JLabel lblGambarToner;
    private javax.swing.JLabel lblHargaFaceWash;
    private javax.swing.JLabel lblHargaSerum;
    private javax.swing.JLabel lblHargaToner;
    private javax.swing.JLabel lblNamaFaceWash;
    private javax.swing.JLabel lblNamaSerum;
    private javax.swing.JLabel lblNamaToner;
    private javax.swing.JButton skin;
    private javax.swing.JButton workout;
    // End of variables declaration//GEN-END:variables
}
