/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.JFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
/**
 *
 * @author Acer
 */
public class skintype extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(skintype.class.getName());

    /**
     * Creates new form skintype
     */
    public skintype(JFrame previous) {
        initComponents();
        setLocationRelativeTo(null);
        
        if (previous != null) {
        this.setLocation(previous.getLocation());
    } else {
        this.setLocationRelativeTo(null);
    }
        
        this.setMinimumSize(new java.awt.Dimension(330, 625));
        setPreferredSize(new java.awt.Dimension(330, 580));
        setSize(340, 590);
        setResizable(false);
        
        confirmblue.setBorderPainted(false);
        confirmblue.setContentAreaFilled(false);
        confirmblue.setFocusPainted(false);
        confirmblue.setOpaque(false);
        
        confirmblue.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nextwhite2.png")));
        
        loadSkinTypeFromDatabase();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        yourskin = new javax.swing.JLabel();
        confirmblue = new javax.swing.JButton();
        skinfoto = new javax.swing.JLabel();
        text4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(31, 119, 245));

        yourskin.setBackground(new java.awt.Color(31, 119, 245));
        yourskin.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        yourskin.setForeground(new java.awt.Color(255, 255, 255));
        yourskin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yourskin.setText("X");
        yourskin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        confirmblue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nextwhite1.png"))); // NOI18N
        confirmblue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        confirmblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmblueActionPerformed(evt);
            }
        });

        skinfoto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        skinfoto.setForeground(new java.awt.Color(255, 255, 255));
        skinfoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        skinfoto.setText("skintype");

        text4.setBackground(new java.awt.Color(31, 119, 245));
        text4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        text4.setForeground(new java.awt.Color(255, 255, 255));
        text4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text4.setText("<html><div style='text-align: center;'>Here’s Your Glow Summary</div></html>");
        text4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(text4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
            .addComponent(skinfoto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(confirmblue, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(yourskin, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(text4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(yourskin, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(skinfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(confirmblue)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadSkinTypeFromDatabase() {
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        try {
            conn = DBConnection.getConnection();
            
            if (conn == null) {
                System.err.println("❌ ERROR: Koneksi database gagal!");
                skinfoto.setText("Error loading data");
                return;
            }
            
            // Ambil skin_type dari database
            String sql = "SELECT skin_type FROM users WHERE id = ?";
            ps = conn.prepareStatement(sql);
            ps.setLong(1, start.Session.userId);
            
            rs = ps.executeQuery();
            
            if (rs.next()) {
                String skinType = rs.getString("skin_type");
                
                if (skinType == null || skinType.isEmpty()) {
                    System.err.println("⚠️ Skin type kosong di database");
                    skinfoto.setText("Your skin type is N/A");
                    return;
                }
                
                System.out.println("✅ Skin Type dari database: " + skinType);
                
                // ✅ Display text di jLabel1: "Your skin type is OILY"
                skinfoto.setText("Your skin type is " + skinType.toUpperCase());
                
                // ✅ Display gambar di text3 sesuai skin type
                displaySkinTypeImage(skinType);
                
            } else {
                System.err.println("⚠️ User tidak ditemukan di database");
                skinfoto.setText("User not found");
            }
            
        } catch (Exception e) {
            System.err.println("❌ Error saat mengambil skin type:");
            System.err.println("   Error Message: " + e.getMessage());
            e.printStackTrace();
            skinfoto.setText("Error: " + e.getMessage());
        } finally {
            try {
                if (rs != null) rs.close();
                if (ps != null) ps.close();
                if (conn != null) conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
    private void displaySkinTypeImage(String skinType) {
        try {
            String imageName = "";
            
            // Map skin type ke nama file gambar
            switch (skinType.toLowerCase()) {
                case "normal":
                    imageName = "Normal.png";
                    break;
                case "oily":
                    imageName = "Oily.png";
                    break;
                case "dry":
                    imageName = "Dry.png";
                    break;
                case "combination":
                    imageName = "Combination.png";
                    break;
                case "sensitive":
                    imageName = "Sensitive.png";
                    break;
                default:
                    imageName = "Normal.png";
                    break;
            }
            
            javax.swing.ImageIcon icon = new javax.swing.ImageIcon(getClass().getResource("/assets/" + imageName));
            
            // Scale gambar jika perlu
            java.awt.Image img = icon.getImage().getScaledInstance(200, 200, java.awt.Image.SCALE_SMOOTH);
            icon = new javax.swing.ImageIcon(img);
            
            yourskin.setIcon(icon);
            yourskin.setText(""); // Hapus text
            
            System.out.println("✅ Gambar berhasil ditampilkan: " + imageName);
            
        } catch (Exception e) {
            System.err.println("❌ Error saat load gambar:");
            System.err.println("   Error Message: " + e.getMessage());
            e.printStackTrace();
            yourskin.setText("❌ Image not found");
        }
    }

    
    private void confirmblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmblueActionPerformed
        Outro donePage   = new Outro(this);
        donePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_confirmblueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
        for (javax.swing.UIManager.LookAndFeelInfo info :
                javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
        logger.log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> new Outro(null).setVisible(true));
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmblue;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel skinfoto;
    private javax.swing.JLabel text4;
    private javax.swing.JLabel yourskin;
    // End of variables declaration//GEN-END:variables
}
