/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Acer
 */
public class start extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(start.class.getName());

    /**
     * Creates new form start
     */
    public class Session {
    public static long userId;
}

    
    public start() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setOpaque(false);
        
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/confirmwhite2.png")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgblue2 = new javax.swing.JPanel();
        text1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bgblue2.setBackground(new java.awt.Color(31, 119, 245));

        text1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        text1.setForeground(new java.awt.Color(255, 255, 255));
        text1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        text1.setText("<html><div style='text-align: center;'>Let’s Personalize Your Experience</div></html>");
        text1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/confirmwhite1.png"))); // NOI18N
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bgblue2Layout = new javax.swing.GroupLayout(bgblue2);
        bgblue2.setLayout(bgblue2Layout);
        bgblue2Layout.setHorizontalGroup(
            bgblue2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgblue2Layout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addGroup(bgblue2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        bgblue2Layout.setVerticalGroup(
            bgblue2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgblue2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(text1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 383, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgblue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgblue2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public java.awt.Dimension getWindowSize() {
        return this.getSize();
    }

    public java.awt.Point getWindowLocation() {
        return this.getLocation();
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try (java.sql.Connection conn = DBConnection.getConnection()) {

        // Insert user kosong dulu
        String sql = "INSERT INTO users () VALUES ()";

        java.sql.PreparedStatement ps = conn.prepareStatement(
                sql, java.sql.Statement.RETURN_GENERATED_KEYS);

        ps.executeUpdate();

        // Ambil ID AUTO_INCREMENT
        java.sql.ResultSet rs = ps.getGeneratedKeys();

        if (rs.next()) {
            long userId = rs.getLong(1);
            Session.userId = userId;

            System.out.println("User ID baru: " + userId);
        }

    } catch (Exception e) {
        e.printStackTrace();
    }
        
        Gender g = new Gender(this);  
        g.setVisible(true);       
        this.dispose();           
    }//GEN-LAST:event_jButton1ActionPerformed

    // ====== HELPER: cek apakah sudah ada user lengkap di DB ======
    private static boolean hasCompletedUser() {
        java.sql.Connection conn = null;
        java.sql.PreparedStatement ps = null;
        java.sql.ResultSet rs = null;

        try {
            conn = DBConnection.getConnection();
            if (conn == null) {
                System.err.println("Koneksi DB gagal (start)");
                return false;
            }

            String sql =
                "SELECT id FROM users " +
                "WHERE bmi_category IS NOT NULL " +
                "  AND exercise_type IS NOT NULL " +
                "LIMIT 1";

            ps = conn.prepareStatement(sql);
            rs = ps.executeQuery();

            if (rs.next()) {
                long existingId = rs.getLong("id");
                Session.userId = existingId;
                System.out.println("Found existing user id: " + existingId);
                return true;
            }
            return false;

        } catch (Exception e) {
            e.printStackTrace();
            return false;
        } finally {
            try { if (rs != null) rs.close(); } catch (Exception ignored) {}
            try { if (ps != null) ps.close(); } catch (Exception ignored) {}
            try { if (conn != null) conn.close(); } catch (Exception ignored) {}
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        
        java.awt.EventQueue.invokeLater(() -> {
            boolean completed = hasCompletedUser();
            System.out.println("DEBUG hasCompletedUser = " + completed);
            System.out.println("DEBUG Session.userId   = " + Session.userId);
            if (completed) {
            new Main(null).setVisible(true);   // ← langsung ke Main
        } else {
            new start().setVisible(true);      // ← ke halaman start (intro)
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgblue2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel text1;
    // End of variables declaration//GEN-END:variables
}
